version: "3"
services:
  nnbot:
    image: nnbot:latest
    container_name: nnbot_main
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
