version: "3"
services:
  nnbot:
    image: nnbot:latest
    container_name: nnbot_main
    build:
      context: .
      dockerfile: "config/Dockerfile.nnbot"
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta

  nnapi:
    image: nnapi:latest
    container_name: nnapi
    build:
      context: .
      dockerfile: "./config/Dockerfile.nnapi"
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta